### ISSUE TITLE
Our First Issue

### ISSUE THREAD

**Issue by bushmusi** [AckonSamuel/space-flight-news#38]
**Project Link:** https://github.com/AckonSamuel/kanban-board.git
**Number of teams:** Two( 2)

**Comment by Amrhub** [comment]
# Approved 💯 ✅ 🥳 🎈 🎉 

Hi Team, 👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to develop it :shipit: 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] [OPTIONAL] number of tasks should be 15 since you are a team of two developers, If you decide to implement other features as you were a team of 3 members, please do it after the core requirements.
Double-check it if you don't want to implement additional features 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
